services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tobechanged
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    image: ghcr.io/evenremy/welsh-academy:latest
    depends_on:
      - db
    ports:
      - 8888:8888

volumes:
  data: