// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ingredients",
				Handler: allingredientsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ingredient",
				Handler: addIngredientsHandler(serverCtx),
			},
		},
	)
}
