# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: cd api ; go build -v welsh-academy.go
    
    - name: Deploy DB from docker-compose
      run: docker-compose up --detach db
    
    - name: Change the api conf
      working-directory: apt/etc/
      run: cat welsh-academy-api.yaml | sed "s/@db/@localhost/" > welsh-academy-api.yaml ; cat welsh-academy-api.yaml

    - name: Test
      run: cd api ; go test -v ./...
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: build
        path: api/api
